name: Build luci-app-fancontrol for GL-AXT1800 (Snapshot)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build package
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: qualcommax-ipq60xx-snapshot
          PACKAGES: luci-app-fancontrol
          FEEDNAME: fancontrol

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ipk
          path: bin/packages/*/*/*.ipk
