name: Build luci-app-fancontrol

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ aarch64_cortex-a53-24.10-SNAPSHOT ]  # Для 24.10-SNAPSHOT SDK, подходящей для GL-AXT1800

    steps:
      - uses: actions/checkout@v4

      - name: Build package
        uses: openwrt/gh-action-sdk@v5
        env:
          ARCH: ${{ matrix.arch }}

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.arch }}
          path: bin/packages/${{ matrix.arch }}/*/*.ipk
          retention-days: 7
